# Generated by Django 2.2 on 2019-05-13 06:47

from django.db import migrations, models
import file_app.models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SHEET_NAME', models.CharField(max_length=20)),
                ('ROW_NO', models.IntegerField()),
                ('COMPANY_NAME', models.CharField(max_length=20)),
                ('STATUS', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=file_app.models.OverwriteStorage(location='media2'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_header', jsonfield.fields.JSONField()),
                ('Template_Name', models.CharField(max_length=80)),
                ('Company_Name', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=20)),
                ('on_off', models.BooleanField(default=True)),
                ('SHEET_NAME', models.CharField(max_length=20)),
            ],
        ),
    ]
